# Generated by Django 5.0.1 on 2026-03-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='static_image_path',
            field=models.CharField(blank=True, help_text='Path to image in static folder (e.g., images/projects/project1.jpg)', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/'),
        ),
    ]
